### ISSUE TITLE
✨ ReservationView(예약하기 화면) Data Binding 및 세부작업

### ISSUE THREAD

**Issue by luminouxx** [Team-JubJub/ZupZup-iOS#15]
## 💬 Description
예약하기 화면의 Data BInding 및 세부적인 작업을 진행할 예정입니다.

## 📝 Todo
- [ ] 가게 정보 받아오기
- [ ] 담은 상품 개수, 총 가격 보여주기
- [ ] 방문예정시간 DatePicker기능 구현
- [ ] 방문자 기능 구현
- [ ] 개인정보 이용 동의 화면 UI 구성
- [ ] 예약 완료하기 유효성 검사
