### ISSUE TITLE
♻️ 1차 UT refactor

### ISSUE THREAD

**Issue by LentoAssai** [Team-JubJub/ZupZup-iOS#184]
## 💬 Description
FCM 설정 수정

## 📝 Todo
- [x] FCM 설정 수정
- [x] Optional Term ViewModel에서의 로직 추가 (항상 false인 버그)
- [x] `KeychainManager` 로깅 추가 및 디버그
- [x] `OrderCheckView` navigation bar 디버그
- [x] 여러번 클릭 시 API 중복 호출 해결 (PlaceOrder, Alarm, Notification)
- [x] FCM 토큰 서버 업데이트 시점 해결 (앱 재시동 시 업데이트 X)
- [x] 애플 로그인 디버그
- [x] 절약 목표금액 수정
- [x] 알림 설정 시 알림 동의 안했을 때 설정으로 이동
- [x] 내 계정 찾기 마지막 화면에서의 pop 및 navigation bar hidden 처리
- [x] `SkeletonView` 디펜던시 제거
- [x] 매장 번호 0이 맨 앞에 붙는 버그
