### ISSUE TITLE
✨ Push 수신 시 처리 로직 구현

### ISSUE THREAD

**Issue by LentoAssai** [Team-JubJub/ZupZup-iOS#189]
## 💬 Description
Push를 수신하였을 때 메시지에 따라 분기 처리 로직을 구현합니다.

## 📝 Todo
- [ ] 취소 - ?
- [ ] 확정 - 마이 페이지로 이동
- [ ] 매장 상품 추가 - 해당 매장 화면으로 이동
- [ ] 매장 정보 수정 - 해당 매장 화면으로 이동
