### ISSUE TITLE
♻️ UI 버그 수정 (상품 이름 길이, 지도 화면 높이)

### ISSUE THREAD

**Issue by LentoAssai** [Team-JubJub/ZupZup-iOS#193]
## 💬 Description
상품 이름 길이와 지도화면의 높이 UI 버그 수정

## 📝 Todo
- [x] `StoreView`에서의 상품 이름 길이
- [x] `ItemView`에서늬 상품 이름 길이
- [x] 지도 화면 높이 수정
