### ISSUE TITLE
♻️ StoresMapView UI 수정

### ISSUE THREAD

**Issue by LentoAssai** [Team-JubJub/ZupZup-iOS#240]
## 💬 Description
`StoresMapView`와 관련한 UI 수정

## 📝 Todo
- [x] DetailCard image maskToBounds 설정
- [x] 카테고리 아이콘 width 수정
- [x] 가게 state (sale, open, close)에 따른 클릭 및 detail card 처리
- [x] Annotation 중복 클릭 시 에러 해결
