### ISSUE TITLE
♻️ UI 변경 작업

### ISSUE THREAD

**Issue by LentoAssai** [Team-JubJub/ZupZup-iOS#43]
## 💬 Description
UI 수정 및 잘못된 부분들을 수정합니다.

## 📝 Todo
- [x] 색상 다시 점검하기
- [x] 탭바 선택 애니메이션 추가하기
- [x] UI 레이아웃 점검하기
- [x] 운영 시간 점검하기
- [x] 예약 loading indicator 화면 구현
