### ISSUE TITLE
♻️LocalStorage CoreData로 교체

### ISSUE THREAD

**Issue by LentoAssai** [Team-JubJub/ZupZup-iOS#69]
## 💬 Description
기존 UserDefaults에 저장하던 데이터들을 CoreData를 이용하여 저장합니다.

## 📝 Todo
- [x] Local Storage 모듈 분리
- [x] Model 작성
- [x] Local Storage Networking API
- [x] Presenter API 호출
