### ISSUE TITLE
✨Firebase SMS 인증

### ISSUE THREAD

**Issue by LentoAssai** [Team-JubJub/ZupZup-iOS#71]
## 💬 Description
Firebase를 통한 SMS 인증을 구현합니다.

## 📝 Todo
- [ ] Firebase 프로젝트에서 전화번호 로그인 활성화 (인증 -> 로그인 -> 전화번호)
- [ ] 앱 인증 사용 설정 (APNs, reCAPTCHA)
- [ ] 인증코드 전송 및 검사 구현
- [ ] 메시지 형식 (from URL) 변경 -> 불가능. App Name으로 나옴. 템플렛은 firebase에서 확인 가능
- [ ] 인증번호 재전송 기능
- [ ] 인증 loading indicator 추가

## Reference
[Firebase Document](https://firebase.google.com/docs/auth/ios/phone-auth?hl=ko)
[Blog 1](https://velog.io/@sookim-1/iOS-FireBase%EB%A5%BC-%ED%86%B5%ED%95%9C-SMS%EC%A0%84%ED%99%94%EB%B2%88%ED%98%B8-%EC%9D%B8%EC%A6%9D%ED%95%98%EA%B8%B0)
[Blog 2](https://fomaios.tistory.com/entry/Firebase-%ED%9C%B4%EB%8C%80%ED%8F%B0%EB%B2%88%ED%98%B8%EB%A1%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%ED%95%98%EA%B8%B0Authenticate-with-Phone-Number)
