### ISSUE TITLE
✨SMS 인증, 회원가입 ui - logic bind

### ISSUE THREAD

**Issue by LentoAssai** [Team-JubJub/ZupZup-iOS#81]
## 💬 Description
회원가입 API를 구현하고 앞서 개발한 UI및 로직들을 bind합니다.

## 📝 Todo
- [x] SMS 인증 Logic bind
- [x] SMS TextField Validation
- [x] 회원가입 API 호출 구현
- [x] 회원가입 API bind
